import tkinter as tk

def f1(num):
   txt = label.cget('text')
   txt += num
   label.config(text=txt)

root = tk.Tk()
root.title('계산기')
label = tk.Label(root, width=25)
label.grid(row=0, column=0)
b1 = tk.Button(root, text='1', width=25, command=lambda : f1('1'))
b1.grid(row=1, column=0)
b2 = tk.Button(root, text='2', width=25, command=lambda : f1('2'))
b2.grid(row=1, column=1)
b3 = tk.Button(root, text='3', width=25, command=lambda : f1('3'))
b3.grid(row=1, column=2)
b4 = tk.Button(root, text='+', width=25)
b4.grid(row=1, column=3)
b5 = tk.Button(root, text='4', width=25, command=lambda : f1('4'))
b5.grid(row=2, column=0)
b6 = tk.Button(root, text='5', width=25, command=lambda : f1('5'))
b6.grid(row=2, column=1)
b7 = tk.Button(root, text='6', width=25, command=lambda : f1('6'))
b7.grid(row=2, column=2)
b8 = tk.Button(root, text='-', width=25)
b8.grid(row=2, column=3)
b9 = tk.Button(root, text='7', width=25, command=lambda : f1('7'))
b9.grid(row=3, column=0)
b10 = tk.Button(root, text='8', width=25, command=lambda : f1('8'))
b10.grid(row=3, column=1)
b11 = tk.Button(root, text='9', width=25, command=lambda : f1('9'))
b11.grid(row=3, column=2)
b12 = tk.Button(root, text='*', width=25)
b12.grid(row=3, column=3)
b13 = tk.Button(root, text='0', width=25, command=lambda : f1(1))
b13.grid(row=4, column=0)
b14 = tk.Button(root, text='C', width=25)
b14.grid(row=4, column=1)
b15 = tk.Button(root, text='=', width=25)
b15.grid(row=4, column=2)
b16 = tk.Button(root, text='/', width=25)
b16.grid(row=4, column=3)
root.mainloop()
